### ISSUE TITLE
modelinfo.json을 활용한 product.html 구성하기

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#1]
@brilliaflo 
modelinfo.json 이용해서 아래의 사진과 같이 product.html을 구성하고 싶습니다.
![image](https://user-images.githubusercontent.com/45654321/57512321-48ee6a00-7346-11e9-968e-1cf24e1e2927.png)
[https://vlaksuga.github.io/chinyoung/modelinfo.json](https://vlaksuga.github.io/chinyoung/modelinfo.json)
[https://vlaksuga.github.io/chinyoung/product.html?model=1](https://vlaksuga.github.io/chinyoung/product.html?model=1)

data-single을 넣었는데 구현이 안되는건지 잘모르겠습니다.
도움 주시면 감사하겠습니다.

**Comment by brilliaflo** [comment]
@vlaksuga 이슈내용이 불명확함.
