### ISSUE TITLE
tile detail에서 속성 값이 없을경우

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#10]
@brilliaflo 
![image](https://user-images.githubusercontent.com/45654321/62866243-43406000-bd4b-11e9-87be-d882bd7a4d4b.png)
그림과 같이 technology 처럼 해당 값이 없으면 속성 명만 보이는데 값이 없을때 속성 명도 안보이게 처리부탁드립니다.

**Comment by brilliaflo** [comment]
t_data 클래스의 텍스트가 없을영우 로우전체를 숨김처리함

**Comment by vlaksuga** [comment]
확인
