### ISSUE TITLE
p_product 모바일에서 9개의 컬렉션만 나옴

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#103]
해당 URL : 모바일 p_product, p_cotto
내용 : 썸네일이 9개만 나옴
- 페이지화 또는 무한 스크롤하게끔 바꿔주세요

**Comment by vlaksuga** [comment]
sev.adand.co.kr에 적용됨 페이지 번호 있음

**Comment by mufasakang** [comment]
확인완료
