### ISSUE TITLE
익스플로러 호환문제

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#105]
1. 익스플로러 호환 문제
새로운 홈페이지 적용 하였으나 익스플로러의 호환문제 이슈로 인한 롤백작업 함.
- 담당자는 알고 있는 사실이였으나, 윗선에서 익스플로러에서의 호환문제가 필요하다고 한 상태
- 다음주 (9월 첫주)에 자체 미팅후 이야기 하기로 함

**Comment by mufasakang** [comment]
1. 11은 ms-grid
2. 그외는 미디어 태그
3. style-ie.css로 해결방안 찾아볼것
- https://css-tricks.com/how-to-create-an-ie-only-stylesheet/

**Comment by vlaksuga** [comment]
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) 로
ie 10, 11은 해결할 수 있음

ie 9버전 이하는 [if ie]로 해결가능
원하는 적용버전이 정해지면 작업하겠음

**Comment by vlaksuga** [comment]
실수로 클로즈 누름

**Comment by mufasakang** [comment]
확인완료
