### ISSUE TITLE
m_all 카달로그 안보임 및 가로모드

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#107]
![image](https://user-images.githubusercontent.com/48310497/64516621-bbd61480-d329-11e9-8eb3-caed54a641a3.png)

![모바일버전 캠쳐본 (3)_가로버전 SNS바로가기](https://user-images.githubusercontent.com/48310497/64516428-7dd8f080-d329-11e9-9705-1bbfe2cd6ad6.png)

- 해당 url : m_all (모바일)
- 내용 : 1. 세로모드에서 안보임
            2. 가로모드에서 줄 밀려 나옴
 어디에 넣어달라는 이야기는 없음
-해결방안 : 1. 삼선앞에 넣는 방법
                   2. 메뉴안에 넣는 방법
![image](https://user-images.githubusercontent.com/48310497/64516921-40289780-d32a-11e9-8b42-5631d77994a4.png)

 2가지 방법 중 공수가 좀 더 수월한 방법으로 하면 될듯

**Comment by vlaksuga** [comment]
sev에 적용함

**Comment by mufasakang** [comment]
![image](https://user-images.githubusercontent.com/48310497/66900623-21f43c80-f038-11e9-90ea-7fe94d7418ae.png)
확인완료
