### ISSUE TITLE
m_all SNS바로가기 안보임 및 가로모드 #107과 고려하여..

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#108]
![image](https://user-images.githubusercontent.com/48310497/64517313-0e640080-d32b-11e9-92ab-5d12260da174.png)

해당url : m_all_SNS바로가기
#107 번과 내용 및 해결방법은 동일함

**Comment by vlaksuga** [comment]
sev에 적용함

**Comment by mufasakang** [comment]
SNS바로가기가 안보임

**Comment by mufasakang** [comment]
확인완료
