### ISSUE TITLE
m_poduct detail modal

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#109]
![image](https://user-images.githubusercontent.com/48310497/64518037-63ecdd00-d32c-11e9-8d64-456cd77005b7.png)

해당 url : m_poduct detail modal
참고 url : http://sev.adand.co.kr/?m=product&cid=80
내용 : 모바일에서 타일 상세에서 타일 클릭시(모달)이 좌우기준 100%로 나오지 않음
ex. 600*600 정사각형이 직사각형 형태로 보임

**Comment by vlaksuga** [comment]
sev에 처리함

**Comment by mufasakang** [comment]
![image](https://user-images.githubusercontent.com/48310497/66901363-88c62580-f039-11e9-9500-7fefafab5b88.png)
확인완료
