### ISSUE TITLE
m_poject detail modal 

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#110]
![image](https://user-images.githubusercontent.com/48310497/64518259-ccd45500-d32c-11e9-83ab-c1a1c8b6c0b4.png)
![image](https://user-images.githubusercontent.com/48310497/64518284-da89da80-d32c-11e9-8418-6154e9e9952e.png)

해당 url : m_poject detail modal
참고 url : http://sev.adand.co.kr/?m=project&pid=1
내용 : 프로젝트 상세에서 클릭시(모달)이 좌우기준 100%로 나오지 않음

**Comment by vlaksuga** [comment]
sev에 적용함

**Comment by mufasakang** [comment]
![image](https://user-images.githubusercontent.com/48310497/66901488-c4f98600-f039-11e9-855b-f6836727c88b.png)
확인완료
