### ISSUE TITLE
m_poduct detail modal 가로모드

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#111]
![모바일버전 캠쳐본 (5)_가로](https://user-images.githubusercontent.com/48310497/64518810-e1fdb380-d32d-11e9-9dd6-9e998d55a8a3.png)

해당 url : m_poduct detail modal
참고 url : http://sev.adand.co.kr/?m=product&cid=80
내용 : 핸드폰 가로모드시 이미지와 같이 화면 짤림

**Comment by vlaksuga** [comment]
sev에 적용함

**Comment by mufasakang** [comment]
![image](https://user-images.githubusercontent.com/48310497/66901617-fa9e6f00-f039-11e9-8a0c-221fe4adfd95.png)

확인완료
