### ISSUE TITLE
m_poject detail modal 가로모드

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#112]
![image](https://user-images.githubusercontent.com/48310497/64519171-95ff3e80-d32e-11e9-8dcf-b194efa7b2a2.png)

해당 url : m_poject detail modal
참고 url : http://sev.adand.co.kr/?m=project&pid=1
내용 : 핸드폰 가로모드시 이미지와 같이 화면 짤림

**Comment by vlaksuga** [comment]
sev에 적용함

**Comment by mufasakang** [comment]
확인완료
