### ISSUE TITLE
p_product 메인 이미지 변경

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#113]
![image](https://user-images.githubusercontent.com/48310497/64519499-32c1dc00-d32f-11e9-8cce-f4869d0e112c.png)

해당 url : http://sev.adand.co.kr/?m=l
내용 : 하기 이미지로 교체

![product_all](https://user-images.githubusercontent.com/48310497/64519652-7ddbef00-d32f-11e9-8c8b-c6e66035bb09.jpg)

**Comment by vlaksuga** [comment]
sev에 적용함

**Comment by mufasakang** [comment]
확인완료
