### ISSUE TITLE
p_search reset버튼 위치 수정

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#114]
![image](https://user-images.githubusercontent.com/48310497/64521004-2ab76b80-d332-11e9-8daa-d5fc468681d5.png)<요청사항>

![image](https://user-images.githubusercontent.com/48310497/64520985-22f7c700-d332-11e9-9fe9-21aff0c94b71.png) <css예시>

1. 해당 url : p_search
2. 내용 : reset버튼 위치 변경

예시화면은 아래와 같이 적용함
`<section id="search_result" class="sec_gap" style="
    margin-top: 120px;
">`
`<h2 style="
    margin-top: 120px;
">SEARCH RESULT</h2>`

**Comment by vlaksuga** [comment]
sev에 적용함

**Comment by mufasakang** [comment]
확인완료
