### ISSUE TITLE
m_search reset버튼 위치 수정

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#115]
![image](https://user-images.githubusercontent.com/48310497/64521429-f1333000-d332-11e9-95d1-de3c46a38950.png)

해당url : m_search
내용 : 
모바일에서 접속시 search의 결과값이 안보여, 검색결과가 없는것 같아 보여 위치조정
#114와 연관하여 모바일과 웹을 따로 조정 할수 없다면, 재 논의 필요

예시화면은 마진을 55px로 조정함
`<section id="search_result" class="sec_gap" style="
    margin-top: 55px;
">`

**Comment by vlaksuga** [comment]
SEV에 적용

**Comment by vlaksuga** [comment]
클로즈만 취소함

**Comment by mufasakang** [comment]
확인완료
