### ISSUE TITLE
p_contact 띄어쓰기 수정

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#116]
![image](https://user-images.githubusercontent.com/48310497/64522224-7cf98c00-d334-11e9-9429-f98f27d697f3.png)

1. 해당 url : p_contact
2. 내용 : 
-진영빌딩(삼전동 38-1)  -> 진영빌딩 (삼전동 38-1)
-전화:031-631-0951 / 팩스:031-631-0952  -> 전화 : 031-631-0951/ 팩스 : 031-631-0952
-월-금 : 7:00AM – 4:00 pm ./ 토.공휴일 : 7AM – 12pm -> 월-금 : 7:00AM – 4:00 pm / 토.공휴일 : 7AM – 12pm

**Comment by vlaksuga** [comment]
sev에 반영함

**Comment by vlaksuga** [comment]
이슈클로즈만 취소

**Comment by mufasakang** [comment]
확인완료
