### ISSUE TITLE
?m=project&pid=1의 실종되었는지 

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#12]
@brilliaflo 
![image](https://user-images.githubusercontent.com/45654321/62867440-396c2c00-bd4e-11e9-8c0d-4db28f153e3e.png)

http://sev.adand.co.kr/?m=projects
에서 ?m=project&pid=1가 안보입니다.

**Comment by brilliaflo** [comment]
아웃도어라거 그런것아닌가요?

**Comment by vlaksuga** [comment]
확인
