### ISSUE TITLE
p_index intro 콜렉션 추가

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#121]
![MAIN 1](https://user-images.githubusercontent.com/48310497/67466360-e97ce000-f681-11e9-87a6-912c5a14b229.jpg)

- 1개추가 (우선순위 1번), 기존 유지
- 링크 : 콜렉션 ID : 60 (비앙코 | BIANCO)

**Comment by vlaksuga** [comment]
처리함

**Comment by mufasakang** [comment]
확인완료
