### ISSUE TITLE
project detail에서 tile이랑 매핑문제

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#13]
@brilliaflo 
![image](https://user-images.githubusercontent.com/45654321/62867902-59501f80-bd4f-11e9-8c9c-d19b09043108.png)

tile 란이 비어있는데 왜그런지 확인좀
안되어있으면 연결좀

**Comment by brilliaflo** [comment]
완료 타일의 프로덕트네임들을 span으로 싸서 뿌렸습니다.

**Comment by vlaksuga** [comment]
span과 span사이에 콤마와 스페이스 한칸 부탁드립니다.

**Comment by brilliaflo** [comment]
<span>,<span>을 추가하였씁니다

**Comment by vlaksuga** [comment]
나머지 값도 매핑해주세요

**Comment by vlaksuga** [comment]
매핑 정보 없다고 안해줌
