### ISSUE TITLE
product 의 tile detail에서 코드번호 노출됨

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#14]
![image](https://user-images.githubusercontent.com/48310497/62868816-771e8400-bd51-11e9-95ff-f91914f33c01.png)

타일 코드 번호가 나오고 있습니다
나오지 않게 해주세요~

**Comment by brilliaflo** [comment]
싸우자

**Comment by mufasakang** [comment]
내부 종결 하겠습니다 ㅠ
