### ISSUE TITLE
project detail 매핑 문제

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#15]
@brilliaflo 
{테이블명.칼럼명}
LOCATION : {project.location}
SPACE : {project.indoor 또는 outdoor=1 이면 indoor, outdoor}
TYPE : {project.residential,commercial,public,furnishing,etc=1 이면 콤마 + 한칸 띄어쓰기로 연속 처리}
AREA : {projec.area}

![image](https://user-images.githubusercontent.com/45654321/62869918-af26c680-bd53-11e9-8556-9beffec46078.png)

**Comment by vlaksuga** [comment]
AREA : {project.area} > 오타수정

**Comment by brilliaflo** [comment]
대충쓰셨으나 찰떡같이알아듣고 콤마도찍고 대문자로 나오게해보았습니다.

**Comment by vlaksuga** [comment]
확인
