### ISSUE TITLE
p_product detail에서 material 빠진건지

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#16]
material 빠진건지 확인좀
![image](https://user-images.githubusercontent.com/45654321/62870708-08dbc080-bd55-11e9-9a42-10abd25aa523.png)

**Comment by brilliaflo** [comment]
나옴
근데 3개만 나옴.css에 맥스 헤이트 있는듯

**Comment by vlaksuga** [comment]
잘처리됨
