### ISSUE TITLE
search에서 size와 thickness처리문제 option 선택시 value를 1

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#17]
search에서 size와 thickness는option 선택시 value를 1,2,3...으로 처리하셨는데
해당 값에 대응하는 value 칼럼을 만들어서 업데이트를 할지 고민입니다.

**Comment by brilliaflo** [comment]
@vlaksuga 이거 제가 그렇게 한것은 아니고 넘어온 html이그렇게 되어있었습니다.

해당 값에 대응하는 것을 넣으면 폼 변경시 컨트롤이 쉬워집니다.

결정의 문제입니다.

**Comment by vlaksuga** [comment]
@brilliaflo
sizevalue와 thicknessvalue라는 칼럼을 만들고 거기에 대응하는 값을 넣어서 처리하면 해결될까요

**Comment by brilliaflo** [comment]
@vlaksuga i can't sure.

**Comment by vlaksuga** [comment]
@brilliaflo 
그렇게 처리하겠음

**Comment by vlaksuga** [comment]
완료
