### ISSUE TITLE
모두보기 ( product,project 페이지)

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#18]
->고객의 요구 : 모르겠고 전체다 보이는 페이지가 필요합니다
![image](https://user-images.githubusercontent.com/48310497/62920379-90badc80-bde0-11e9-8f00-f6494c247fd2.png)

1. NAV에서 프로덕트를 누르면 모든 콜렉션이 보이게 (순서는 최신업데이트순 또는 ID역순)
-필요하다면 ALL 메뉴를 추가해도 됨

2. NAV에서 프로젝트를 누르면 모든 프로젝트가 보이게 (순서는 최신업데이트순 또는 ID역순)
-필요하다면 ALL 메뉴를 추가해도 됨

*이런경우 이슈를 1,2 각각 발행해야 하는지 같은 이슈에 적어야 되는지 알려주시면
다음부터 그렇게 하겠습니다.

**Comment by brilliaflo** [comment]
우예할지 알려줘야 짜지

**Comment by vlaksuga** [comment]
1. MENU는 없습니다. PRODUCTS CLICK시에 p=all
2. MENU는 없습니다. PROJECTS CLICK시에 P=all

**Comment by vlaksuga** [comment]
PRODUCT OK, PROJECT YET

**Comment by mufasakang** [comment]
PROJECT 는 새로운 이슈 발행 하였습니다.
