### ISSUE TITLE
썸네일에 브랜드 대신 디자인명이 보이게 해주세요

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#19]
고객의 요구 : 썸네일에 브랜드 대신 디자인명이 보이게 해주세요
![image](https://user-images.githubusercontent.com/48310497/62920675-687fad80-bde1-11e9-8063-386c4979b6f2.png)

1개의 COLLECTION은 1개의 DESIGN밖에 가질수 없다. 라고 광고주와 이야기 하였습니다.
(1개의 COLLECTION에서 다른 DESIGN이 생길경우 COLLECTION ID를 추가 발급하여 운영하기로 함)

**Comment by brilliaflo** [comment]
이거 도 어디에인지
알려줘야함

**Comment by vlaksuga** [comment]
p_product와 p_search의 tile 입니다.
collection 테이블에 cdesign 칼럼 생성후 삽입해서 처리하겠음

**Comment by vlaksuga** [comment]
테이블 변형없이 해결함
