### ISSUE TITLE
p_product_detail에서 tile image 불러오기

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#2]
@brilliaflo 
## p_product_detail.php에 관한 내용임

-  tile 테이블에서 imgs를 불러와야함

![image](https://user-images.githubusercontent.com/45654321/62855816-2ba6ae80-bd2e-11e9-98ba-525f010fb2e6.png)

**Comment by brilliaflo** [comment]
타일을 불러와서 이미지를 띄웠습니다만 드른정보매핑은 하지못하였습니다
이슈를 발행해주시면 처리하도록하겠습니다.

**Comment by vlaksuga** [comment]
확인함
