### ISSUE TITLE
Collection에 New처리에 관하여

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#20]
@brilliaflo 
아래의 그림과 같이 collection에 new를 처리하고자 합니다.
![image](https://user-images.githubusercontent.com/45654321/62922226-dc23b980-bde5-11e9-94ab-bbfc3dddc7cc.png)
```
          <div class="tile">
                <img src="img/thumb/thumb1.jpg" alt="thumb1">
                <div class="detail">
                    <h2>CALACATTA</h2>
                    <p>MARBLE</p>
                </div>
                <div class="new">NEW</div>
            </div>
```
1. class를 new로 합니다.
2. css는 아래와 같습니다.

```
.new {
    position: absolute;
    right:5px;
    top:5px;
    background-color: navy;
    color:white;
    border-radius: 50%;
    width: 50px;
    height: 50px;
    padding-top: 15px;
    text-align: center;
    font-weight: bolder;
}
```

3. collection 테이블에 new라는 칼럼을 추가서 new=1로 처리하는게 어떨지요

답변주시면 처리하겠습니다.

**Comment by brilliaflo** [comment]
as you wish

**Comment by vlaksuga** [comment]
그렇게 진행하겠습니다.

**Comment by vlaksuga** [comment]
tile테이블에 new 칼럼을 추가하여 new=1인것을 포함한 collection에 new처리함

**Comment by brilliaflo** [comment]
https://github.com/vlaksuga/chinyoung/issues/20#issuecomment-520838630
@vlaksuga 타일에 뉴는 1이거나 널입니까?

**Comment by vlaksuga** [comment]
tile/new는 1이거나 null입니다.
