### ISSUE TITLE
kerlite가 먼저 보이게 해주세요

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#21]
요청사항 : http://sev.adand.co.kr/?m=l&p=kerlite 에서 콜렉션 명에 kerlite가 있는 썸네일이 먼저 뜨게 해주세요 (순서는 최신등록순 또는 ID역순)

kerlite 외의 타일들의 순서는 최신등록순 또는 ID역순

**Comment by vlaksuga** [comment]
collection에 weight 칼럼을 만들고 숫자가 높은 순서대로 보여준다

**Comment by brilliaflo** [comment]
as you wish..
we wish your xmas

**Comment by mufasakang** [comment]
정리된 노출순서는 다음과 같습니다
url : p_products
기본: ID 역순으로 노출
우선순위
1. NEW Kerlite
2. NEW
3. Kerlite
4. 그외

**Comment by brilliaflo** [comment]
> collection에 weight 칼럼을 만들고 숫자가 높은 순서대로 보여준다

이거 멍미
https://github.com/vlaksuga/chinyoung/issues/21#issuecomment-521109386
이거랑 어떻게 해야하는거임

**Comment by mufasakang** [comment]
#44 로 다시 정리하였습니다
