### ISSUE TITLE
p_product_detail 의 표기 변경

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#22]
![image](https://user-images.githubusercontent.com/48310497/62923105-f65e9700-bde7-11e9-8a58-a449239599e7.png)
1. Brand -> Design 이름으로 변경

![image](https://user-images.githubusercontent.com/48310497/62923165-168e5600-bde8-11e9-9e97-e596708127a7.png)
2. Design 삭제
    Brand 추가

![image](https://user-images.githubusercontent.com/48310497/62923288-60773c00-bde8-11e9-84b4-1a9427bd79c0.png)
3. KERLITEANTI-BACTERIAL 이 한줄로 나오게

**한페이지의 내용이라 한번에 적었는데, 따로 적어야 되면 앞으로 그렇게 하겠습니다

**Comment by vlaksuga** [comment]
3. KERLITEANTI-BACTERIAL > KERLITE, ANTI-BACTERIAL 이 한줄로 나오게
**한페이지의 내용이라 한번에 적었는데, 따로 적어야 되면 앞으로 그렇게 하겠습니다

**Comment by vlaksuga** [comment]
css로 마무리 하겠음

**Comment by vlaksuga** [comment]
완료
