### ISSUE TITLE
p_project_detail 에서 이미지 클릭시 확대

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#23]
http://sev.adand.co.kr/?m=project&pid=2

이미지 클릭시 확대 해주세요
p.s 확대된 상태에서 옆에 화살표 누르면 넘어가게 해주실수 있나요?

**Comment by brilliaflo** [comment]
디자이너 일해라

**Comment by vlaksuga** [comment]
@brilliaflo 
#3 와 같은 디자인으로 처리하되
#6 에서 사용된 텍스트 영역은 사용하지 않음

그리고 띄워진 모달을 좌우로 넘겨서 이미지를 전환할 수 있게 하기

**Comment by vlaksuga** [comment]
적폐시전함

**Comment by vlaksuga** [comment]
완료
