### ISSUE TITLE
products 메뉴에 metal 추가

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#26]
![image](https://user-images.githubusercontent.com/48310497/62947656-dea20580-be1d-11e9-8562-ed8158eceaaa.png)

http://sev.adand.co.kr/?m=l
메뉴의 brick/decor와 colour에 "metal" 추가 해주세요

metal클릭시 metal design 노출

**Comment by vlaksuga** [comment]
처리완료
