### ISSUE TITLE
썸네일 이미지 변경 (잘보이게)

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#27]
![image](https://user-images.githubusercontent.com/48310497/62948204-ea41fc00-be1e-11e9-9634-62954e3c5bd9.png)

![image](https://user-images.githubusercontent.com/48310497/62948354-28d7b680-be1f-11e9-8dfd-b1080b9bc6a4.png)

#19의 해당 영역의 썸네일에 글씨가 잘 안보입니다.
2번째 이미지 처럼흰색 배경처리 해주세요.

p_product와 p_search의 tile 입니다.

**Comment by vlaksuga** [comment]
완료
