### ISSUE TITLE
p_index 에서 타일밑에 viewmore 링크지정

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#29]
![image](https://user-images.githubusercontent.com/48310497/62997308-c7592b80-bea2-11e9-8075-02398430f768.png)

해당 url : http://sev.adand.co.kr/
내용 : 타일밑에 있는 viewmore 클릭시 어디론가 날아갈수 있게 해주세요. 천국도 괜찮아요

**Comment by vlaksuga** [comment]
done
