### ISSUE TITLE
p_index 에서 메인 viewmore 링크지정

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#30]
![image](https://user-images.githubusercontent.com/48310497/62997389-0b4c3080-bea3-11e9-9909-7c40b1c32f13.png)

#29 와 같은 내용이나
해당영역은 메인 페이지의 메인이미지 입니다.

**Comment by vlaksuga** [comment]
이미지가 어느 collection 소속인지 확인이 불가해서 예시로 적어놨습니다.

**Comment by vlaksuga** [comment]
done
