### ISSUE TITLE
p_product_detail 에서 BRaNd

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#31]
![image](https://user-images.githubusercontent.com/48310497/62997516-8b729600-bea3-11e9-8284-326afe5bdf7b.png)

해당 url : p_product_detail
예시 url : http://sev.adand.co.kr/?m=product&cid=1
내용 : BRaNd 를 BRAND로 수정해주세요

**Comment by vlaksuga** [comment]
done
