### ISSUE TITLE
p_search에서 A,B,C.. .alpha 마우스 오버 효과 넣어주세요

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#33]
![image](https://user-images.githubusercontent.com/48310497/63001958-be228b80-beaf-11e9-9c0a-48471b10c7ac.png)

해당url : http://sev.adand.co.kr/?m=search
내용 : 마우스 오버시 손가락 모양으로 나오게 해주세요

**Comment by vlaksuga** [comment]
완료
