### ISSUE TITLE
p_search에서 reset 버튼 위치 및 ui변경

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#34]
![image](https://user-images.githubusercontent.com/48310497/63002353-b9aaa280-beb0-11e9-862b-7b698a3999c7.png)

해당 url : http://sev.adand.co.kr/?m=search
내용 : reset 버튼 위치및 ui변경
위치 : SEARCH RESULT 옆으로 변경
ui : 모양 변경 및 동그란 화살표 추가 (이미지 참고)
![image](https://user-images.githubusercontent.com/48310497/63002311-9f70c480-beb0-11e9-80f6-b0fd7abaf04a.png)
![image](https://user-images.githubusercontent.com/48310497/63002316-a4357880-beb0-11e9-9802-9517f7719623.png)

**Comment by vlaksuga** [comment]
완료
