### ISSUE TITLE
p_project 에서 메뉴 색 적용 빼주세요

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#35]
![image](https://user-images.githubusercontent.com/48310497/63004179-bd402880-beb4-11e9-9c4c-df4eabbcce0a.png)

p_project 메뉴와 같게 해주세요

![image](https://user-images.githubusercontent.com/48310497/63004238-de087e00-beb4-11e9-964c-da477e867675.png)

**Comment by vlaksuga** [comment]
완료
