### ISSUE TITLE
p_project_detail 에서 영역 삭제요청

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#36]
![image](https://user-images.githubusercontent.com/48310497/63004721-05ac1600-beb6-11e9-8b66-8ff4eeb90574.png)

해당 url : p_project_detail
참고 url : http://sev.adand.co.kr/?m=project&pid=2

해당영역삭제 해주세요

**Comment by vlaksuga** [comment]
Comment 처리함
