### ISSUE TITLE
p_search 조건검색 셀렉트를 다시 선택할수 있게

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#38]
![image](https://user-images.githubusercontent.com/48310497/63011116-9daffc80-bec2-11e9-9bdd-1d86de1e866f.png)

해당 url : http://sev.adand.co.kr/?m=search
내용 : 예)space에서 indoor를 고르고 다시 전체를 보고싶어 space를 눌러서 조건을 취소 하고 싶은데 할수가 없어요
적용범위 : space,size~~~technology 까지

**Comment by mufasakang** [comment]
추가내용)첫번째 옵션만 색깔을 다르게

**Comment by vlaksuga** [comment]
완료
