### ISSUE TITLE
p_product_detail에서 타일 모달이미지 좌우버튼 추가

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#39]
![image](https://user-images.githubusercontent.com/48310497/63011538-7f96cc00-bec3-11e9-92c9-284f12826888.png)

 #23 과 같은내용
띄워진 모달을 좌우로 넘겨서 이미지를 전환할 수 있게 하기

해당url : p_product_detail

**Comment by mufasakang** [comment]
확인하였습니다.

**Comment by vlaksuga** [comment]
done
