### ISSUE TITLE
product에서 p= 조건에 따라 색칠 되고 안되고 현상

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#4]
http://sev.adand.co.kr/?m=l&p=kerlite

![image](https://user-images.githubusercontent.com/45654321/62859270-9a3c3a00-bd37-11e9-9a9c-95641b9e07b9.png)
![image](https://user-images.githubusercontent.com/45654321/62859284-a45e3880-bd37-11e9-9a96-7e5b3e4396d2.png)

아래 소메뉴에 흰색 체크 되고 안되고 차이를 봐주시면 감사하겠습니다.

**Comment by brilliaflo** [comment]
data-p ㅂㅐㄹ류 변경함

**Comment by vlaksuga** [comment]
확인함 완료
