### ISSUE TITLE
p_index viewmore 버튼 통일되게

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#41]
![image](https://user-images.githubusercontent.com/48310497/63012472-45c6c500-bec5-11e9-9bb2-1b4f18c47d41.png)
![image](https://user-images.githubusercontent.com/48310497/63012549-6858de00-bec5-11e9-8a2b-680e81770e8a.png)

해당 url : http://sev.adand.co.kr/
내용 : view more 크기 모양 다 같게. 기준은 메인이미지의 viewmore

**Comment by vlaksuga** [comment]
완료
