### ISSUE TITLE
p_product 썸네일안의 글씨 색 변경

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#42]
![image](https://user-images.githubusercontent.com/48310497/63014311-35184e00-bec9-11e9-8573-2f664e1e9b72.png)

해당 url : p_index, p_product
내용 : css386 의 색상 변경 요청 (darkgray)

**Comment by vlaksuga** [comment]
완료

**Comment by mufasakang** [comment]
#353535 색상으로 변경 부탁드립니다

**Comment by vlaksuga** [comment]
완료
