### ISSUE TITLE
KERLITE NEW 등 노출 순서에 관한 SWITCH

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#45]
@brilliaflo 

collection은 sortpoint의 내림차순으로 정렬하고, sortpoint가 같다면 collectionid의 내림차순으로 정렬한다.

collection의 sortpoint의 기본값은 0이다.
tile에서 kerlite=1이 하나라도 포함된 collecotion은 sortpoint 2
tile에서 new=1이 하나라도 포함된 collecotion은 sortpoint 3

collection의 sortbonus 칼럼은 +와 -를 사용해 sortpoint에 숫자를 더하거나 뺄 수 있다.
collection에는 status가 있고, 1이면 노출(디폴트), 0이면 숨김처리한다.

**Comment by brilliaflo** [comment]
개 똥 멍청이

**Comment by brilliaflo** [comment]
kerlite의 소트 보너스는 2
new의 소트보너스는 3

컬렉션의 최종소트보너스는 소트보너스들의 합으로 한다

로 하겠습니다.

**Comment by vlaksuga** [comment]
collection/status=1 이면 보임, =0이면 숨김 (디폴트는 1)
tile/kerlite=1이 하나라도 포함된 collection의 sortbonus=+2
tile/new=1이 하나라도 포함된 collection의 sortbonus=+3
collection/sortpoint는 +, -로 입력가능한 숫자로 sortbonus에 더하거나 뺀다
collection은 sortbonus의 합으로 내림차순으로 정렬하고, 같으면 collectionid로 내림차순한다.

**Comment by brilliaflo** [comment]
@mufasakang @vlaksuga 전체 쿼리를 고쳤으느
전체적으로다가 테스트 필요

**Comment by vlaksuga** [comment]
완료
