### ISSUE TITLE
콜렉션 썸네일에 숫자와 회색띠가 보임

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#46]
![image](https://user-images.githubusercontent.com/48310497/63026986-188b0e80-bee7-11e9-9171-668ce69a069f.png)
![image](https://user-images.githubusercontent.com/48310497/63027137-59832300-bee7-11e9-9f09-6c7c2c0343e3.png)

해당 url :p_product, p_index, p_search
내용 : 콜렉션 썸네일에 숫자와 회색띠가 노출됨, 없애주세요
          아마도 #20 작업 이후인것 같습니다..

**Comment by brilliaflo** [comment]
@mufasakang 유아이 문제임으로 디자인파트로 이관해주세요

**Comment by vlaksuga** [comment]
done
