### ISSUE TITLE
p_project 페이지에서 파란색 원을 없애주세요

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#48]
![image](https://user-images.githubusercontent.com/48310497/63030431-3d828000-beed-11e9-8263-06b905688339.png)

해당 URL : http://sev.adand.co.kr/?m=projects
내용 : 파란색원이.... 나와요 없애주세요ㅠ

**Comment by brilliaflo** [comment]
핑퐁

**Comment by vlaksuga** [comment]
done
