### ISSUE TITLE
searchhint 겹침 문제

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#49]
http://sev.adand.co.kr/?m=search&&hint=N와
http://sev.adand.co.kr/?m=search&&hint=num이 겹치므로

http://sev.adand.co.kr/?m=search&&hint=num를
http://sev.adand.co.kr/?m=search&&hint=1로 해주시면
db는 제가 바꾸겠음

**Comment by brilliaflo** [comment]
@vlaksuga 바꾸시는김에 거P_search보시면

``` <li><a  onclick="sh('num')">0-9</a></li>```

num을 1로

**Comment by vlaksuga** [comment]
완료
