### ISSUE TITLE
p_product에서 cotto d'este 처리하기

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#5]
@brilliaflo 

![image](https://user-images.githubusercontent.com/45654321/62862566-2737c100-bd41-11e9-9334-277f6ca8a677.png)

p_main.php에서 아래 그림의 view more를 클릭하면

![image](https://user-images.githubusercontent.com/45654321/62864729-7aad0d80-bd47-11e9-9000-076a32c2b3d9.png)

p_product에서 brand가 cotto d'este 인 collection만 보여지는 페이지를 만들어서 이동시켜주세요

**Comment by brilliaflo** [comment]
무ㅅㅅ,ㄴ 문제인지 모르겠읍니다.

**Comment by brilliaflo** [comment]
브랜드 검색을 추가하였씁니다

코토는 
./?m=l&p=cotto
입니다

**Comment by vlaksuga** [comment]
확인
