### ISSUE TITLE
p_search 에서 알파벳의 결과값이 없으면 안보이게 해주세요

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#51]
![image](https://user-images.githubusercontent.com/48310497/63031828-a539ca80-beef-11e9-8a65-6143bbfe478c.png)

해당url :p_search
내용 : 해당 컬렉션이 없으면 안보이개 해주세요
         현재는 z,u,t,q,k,i 이 없습니다

**Comment by vlaksuga** [comment]
done
