### ISSUE TITLE
p_project 썸네일에서 회색 띠가 몇몇 보임

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#53]
![image](https://user-images.githubusercontent.com/48310497/63094679-06bb7100-bfa4-11e9-8c39-ed5584ff00ee.png)
해당 URL : p_project
내용 : 전체가 아닌 일부 몇몇 썸네일에 회색띠가 보임
#46 과 관련이 있는지는 모르겠음..

**Comment by mufasakang** [comment]
![image](https://user-images.githubusercontent.com/48310497/63094934-c3adcd80-bfa4-11e9-8d10-28aacc413595.png)

p_product 썸네일에서도 나옴...
2,3번째 위치인 공통점은 있음..

**Comment by vlaksuga** [comment]
#40 처리하는 과정에서 34% 33% 33%로 넓이 조정을 해서 배경이미지가 상이하게 나오는 것으로 보임
33.3%로 동일하게 처리해보고 확인해볼 예정

**Comment by vlaksuga** [comment]
처리완료
