### ISSUE TITLE
p_product_detail에서 tile detail 처리하기

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#6]
@brilliaflo 
$imgs  

$productname

code | $tilid
design | $effect
space | $indoor/outdoor
material | $material
technology | $kerlite/bigslab/antislip/antibacterial
finish | $finish/finish2
size | $sizes 중에 사이즈
thickness | $sizes 중에 두께

이렇게 처리해 주시고 기존에 html 또는 p_product_detail에 있던 colour 등은 삭제 바랍니다.
아!! 만약 html에 없으면 다른컬럼과 동일하게 복사해주시면 됩니다.
![image](https://user-images.githubusercontent.com/45654321/62863468-d5446a80-bd43-11e9-9f7e-16ce6043f37d.png)

**Comment by brilliaflo** [comment]
수정해도 무소용.
