### ISSUE TITLE
p_project에서 RESIDENTIL 선택시 전체 나옴

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#62]
![image](https://user-images.githubusercontent.com/45654321/63421624-e415d600-c443-11e9-9092-1216b3e3b7ff.png)
![image](https://user-images.githubusercontent.com/45654321/63421683-fbed5a00-c443-11e9-9c99-a4eb940ccbed.png)
residential은 db상 6개인데 9개 나옴

**Comment by vlaksuga** [comment]
@brilliaflo 처리부탁드립니다.

**Comment by vlaksuga** [comment]
위치는 아래와 같습니다.
http://sev.adand.co.kr/?&m=projects&cate=residential

"residential"에 대한 결과물이 9개 나옵니다.

왜냐면
![image](https://user-images.githubusercontent.com/45654321/63599090-ce4b1100-c5fb-11e9-811e-09ee672fdaf0.png)

DB에는 "residential" 이 총 6개 입니다.

`<li><a <? if($cate=="residential") {?>class="active"<? }?> href="?&m=projects&cate=residential">RESIDENTIAL</a></li> `

오타도 살펴봤는데 이유를 잘 모르겠습니다.
확인 부탁드립니다.

**Comment by mufasakang** [comment]
확인완료

**Comment by vlaksuga** [comment]
확인함
