### ISSUE TITLE
cotto d'este 서브메뉴바 삭제

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#64]
cotto d'este 서브메뉴바 삭제가
![image](https://user-images.githubusercontent.com/45654321/63423457-51773600-c447-11e9-9b3b-4cbfc66a70b2.png)
그림의 로고밑에 파란색 줄을 의미하는 것인지 확인 후 @mufasakang  수정할 예정

**Comment by vlaksuga** [comment]
삭제해놓음

**Comment by mufasakang** [comment]
![image](https://user-images.githubusercontent.com/48310497/63577861-4567b180-c5ca-11e9-801b-97974a598245.png)

p_cottoseste 에서 
ALL KERLITE/BIG SLAB MARBLE STONE CONCRETE TERRACOTTA WOOD BRICK/DÉCOR METAL COLOUR OUTDOOR
가 적힌 메뉴를 지워달라는 이야기

**Comment by vlaksuga** [comment]
해당 주소는 아래와 같습니다.
sev.adand.co.kr/?m=l&p=cotto

**Comment by brilliaflo** [comment]
section#products_tiles > div.group 에 cotto일경우 .cotto 추가함

**Comment by vlaksuga** [comment]
http://sev.adand.co.kr/?m=l&p=cotto 페이지가 열리지 않습니다.
페이지가 열리면 .cotto를 css로 display=none 처리하겠습니다.

**Comment by vlaksuga** [comment]
`<div class="group ">` 으로 나옴
`<div class="group cotto">` 로 나와야함
![image](https://user-images.githubusercontent.com/45654321/63676652-62002580-c826-11e9-9a1d-cd626e8286cb.png)

**Comment by vlaksuga** [comment]
`<?php if( trim($p) == "cotto" ) echo "cotto";?>`
p_products 30번줄, 작동안함

**Comment by vlaksuga** [comment]
확인후 완료

**Comment by mufasakang** [comment]
확인완료
