### ISSUE TITLE
p_project에 서브메뉴바에 ALL 추가

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#65]
![image](https://user-images.githubusercontent.com/45654321/63423581-913e1d80-c447-11e9-816b-398ca1c9c10d.png)

내용 확인함

**Comment by vlaksuga** [comment]
`<li><a href="?&m=projects">ALL</a></li>`
로 처리하였음.
아래와 같이 ACTIVE 처리를 위해 @brilliaflo 도움을 요청합니다.
`<li><a <? if($cate=="indoor") {?>class="active"<? }?> href="?&m=projects&cate=indoor">INDOOR</a></li>`

**Comment by brilliaflo** [comment]
머 우예하라는지 모르겠어서
그냥 ALL에 active 추가하겠습니다

**Comment by vlaksuga** [comment]
완료
