### ISSUE TITLE
P_PRODUCTS TILE DETAIL 확대시 제품이미지 센터에 위치 

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#66]
![image](https://user-images.githubusercontent.com/45654321/63423682-ce0a1480-c447-11e9-86c9-8fa731176cf4.png)
직사각형과 정사각형을 이미지 시작점을 TOP 기준으로 잡았으나 이부분을 이미지의 중간을 기준으로 배열할 수 있도록 알아보고 처리하겠음.

**Comment by vlaksuga** [comment]
처리함 확인후 완료

**Comment by mufasakang** [comment]
확인완료
