### ISSUE TITLE
SEARCH THICKNESS에서 옵션 변경에 따른 DATA 정리

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#67]
`<option value="2">8T</option>`
에서
`<option value="2">7T - 8T</option>`
로 수정하고, 해당 VALUE에 해당하는 타일을 재정리할것

**Comment by vlaksuga** [comment]
<option value="2">7T - 8T</option> 이지만
실제로는 
7.2T,   7.5T, 8.5T (7T 이상 ~ 9T 미만) 까지 value=2로 처리해달라는 요청

**Comment by vlaksuga** [comment]
처리함

**Comment by mufasakang** [comment]
SEARCH THICKNESS에서 두번째 옵션인
7T-8T표기를 7T-8.5T표기로 변경

**Comment by vlaksuga** [comment]
처리함
