### ISSUE TITLE
FOOTER 주소와 문구등

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#69]
@mufasakang 
[FOOTER]    

1. 주소 및 표기방식 변경 (도로명 주소로 변경, 이천 물류센터는 도로명 없음)

본사 PREMIUM TILE GALLERY TEL|02-416-0417 FAX|02-416-6292
(주)진영코리아 | 서울시 송파구 삼전로2길 3,진영빌딩 (삼전동 38-1)

논현 TILE PLAZA TEL|02-543-5117 FAX|02-543-5104
서울특별시 강남구 학동로24길 16 (논현동 127-7)

이천 제1물류센터 TEL|031-631-0951 FAX|031-631-0952 경기도 이천시 모가면 송곡2리 166-5 

삼패 제2물류센터 경기도 남양주시 경강로334번길 48-12 (삼패동 445-4)    

2. 쇼룸이름과 전화번호가 바로 이어져서 가독성이 떨어짐. 
 
3. COPYRIGHT 문구 : 주소 정보보다 눈에 덜 띄게

**Comment by vlaksuga** [comment]
2. 가독성이 떨어짐 해결방안 제시요망
3. 크기를 줄이는 것으로 해결하겠음

**Comment by vlaksuga** [comment]
1. 주소는 변경처리함

**Comment by mufasakang** [comment]
"삼패 제2물류센터" 문구추가
삼패 제2물류센터 경기도 남양주시 경강로334번길 48-12 (삼패동 445-4)

**Comment by mufasakang** [comment]
![image](https://user-images.githubusercontent.com/48310497/63579899-9aa5c200-c5ce-11e9-80a4-440c04d56737.png)

2. 가독성에 대한 제안용
->통화당시 가독성에 대한 이야기는 없었음

**Comment by mufasakang** [comment]
![image](https://user-images.githubusercontent.com/48310497/63579987-c1fc8f00-c5ce-11e9-9183-1202cfbcba52.png)
텍스트 컬러 grey로 변경

**Comment by vlaksuga** [comment]
완료
