### ISSUE TITLE
p_product_detail에서 modal 실행시

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#7]
@brilliaflo 
![image](https://user-images.githubusercontent.com/45654321/62863922-39b3f980-bd45-11e9-80a6-5afe9caeccca.png)

파라메터를
$imgs
$productname
$sizes
로 처리 부탁드립니다

**Comment by brilliaflo** [comment]
값셋팅을 하였습니다.
근데 디자인은요?

**Comment by vlaksuga** [comment]
저게 디자인인데요
