### ISSUE TITLE
CONTACT 운영시간 등

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#70]
[CONTACT]

1. 본사전시장 운영시간 정정

월 - 토. 공휴일 : 9AM - 6pm / 일요일 : 휴무

2 .논현점 주소 변경
서울특별시 강남구 학동로24길 16 (논현동 127-7)

3. 삼패 제2물류센터 주소변경
경기도 남양주시 경강로334번길 48-12 (삼패동 445-4)

**Comment by vlaksuga** [comment]
처리함 확인후 종료

**Comment by mufasakang** [comment]
확인완료
