### ISSUE TITLE
p_search에서 FINISH항목의 HONED 가 노출안됨 

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#72]
![image](https://user-images.githubusercontent.com/48310497/63576864-0e909c00-c5c8-11e9-8774-443e3870ddec.png)

LAPPATO만 나옴

**Comment by vlaksuga** [comment]
finish1 : HONED 를 LAPPATO로 수정하고
finish3 : HONED를 추가해서 수정함
