### ISSUE TITLE
about 본문 내용 변경

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#74]
p_about의 기존내용 삭제, 해당글로 본문 변경
---------------------------
![image](https://user-images.githubusercontent.com/48310497/63581036-0b4dde00-c5d1-11e9-8c12-8de8ce6b1fbd.png)

지난 수십년간 비약적인 기술개발로 진화를 거듭해온 '타일'은 이제 더 이상 우리가 알던 그 '타일'이 아닙니다. 인테리어 마감재를 넘어 건축물의 외장재로, 테이블이나 주방가구 등 카운터 상판, 혹은 가구 마감재로 타일의 사용처는 끊임없이 확장되고 있습니다. 

(주)진영코리아는 이탈리아 타일 전문 수입공급원으로 파나리아 그룹(PANARIA GROUP)의 코토데스테(COTTO D'ESTE)를 비롯한 엄선된 제품을 통해 그 흐름을 주도하고 있습니다. 보편성을 바탕으로 트렌드와 최신기술이 접목된 최상의 품질, 풍부한 디자인과 다양한 사이즈, 합리적이고 폭넓은 가격대, 원활하고 안정적인 공급은 진영의 자부심입니다. 공간 디자인에 대한 전문성을 강화해 전문가와 소비자를 대상으로 포괄적인 컨설팅과 제품 공급을 목표로 하고 있습니다.

오로지 '타일'만으로 어떠한 건축물이라도 완성시킬 수 있는 지금.
본사 전시장 혹은 논현점을 방문해 타일의 신세계를 직접 경험해보세요.

CUSTOMER 소비자 문의 / WHOLESALE 유통 문의 / PROJECT 프로젝트 문의

**Comment by vlaksuga** [comment]
확인후 클로즈
