### ISSUE TITLE
p_about의 FAQ내용 수정

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#75]
![image](https://user-images.githubusercontent.com/48310497/63581176-6384e000-c5d1-11e9-8fb0-8fd2ecd2a5b3.png)

1.	제품 종류가 많은데 어떤 제품이든 바로 구입할 수 있나요?
홈페이지에 등록된 모든 제품은 직수입을 통해 국내재고를 확보하고 있습니다.
2개소 약 6000평 규모의 물류센터에 풍부한 수량을 보관하고 있어 지정일에 출고가 가능합니다.
간혹 일시품절되는 제품도 있으나 대부분의 제품은 언제든지 구매가능합니다.

2.	제품을 구매하고 싶은데 소량도 판매하나요?
㈜진영코리아의 모든 제품은 수량과 관계없이 구매하실 수 있습니다. 
언제든지 전시장 운영시간에 들러서 직접 살펴보시고 주문하실 수 있습니다.
방문 전 예약하시면 더욱 편안하게 이용하실 수 있습니다. 

3.	구체적인 제품 상담을 하고 싶은데 어떻게 해야 하나요?
㈜진영코리아는 공간과 디자인에 대한 전문성을 갖춘 컨설팅을 추구하고 있습니다.
상담 예약을 하시면 원하는 시간대에 보다 편리하고 상세하게 상담 받으실 수 있습니다.
원활한 상담을 위해 상담 예약을 추천드립니다.

**Comment by vlaksuga** [comment]
확인
