### ISSUE TITLE
p_contact 내용 수정

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#76]
![image](https://user-images.githubusercontent.com/48310497/63581313-ba8ab500-c5d1-11e9-9d14-335fa4c3a694.png)
해당당 문구 수정
---------
*상담 예약을 하시면 원하는 시간대에 보다 편리하게 상담 받으실 수 있습니다. 
예약방문이 아닐 경우 원활한 상담이 어려울 수도 있으니 상담 예약을 추천드립니다.

**Comment by vlaksuga** [comment]
CONTACT 문구 수정
