### ISSUE TITLE
p_about의 이미지 변경 및 제목삭제

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#78]
![image](https://user-images.githubusercontent.com/48310497/63582558-41409180-c5d4-11e9-9912-f88d3c24c387.png)
1.  해당 제목 삭제
PRIMIUM TILE GALLERY
프리미엄 타일갤러리

2. 이미지 변경
![1_SITE 20170707_135650](https://user-images.githubusercontent.com/48310497/63582622-61705080-c5d4-11e9-98e5-8885eef111e2.jpg)
![2_SITE 20170707_140645](https://user-images.githubusercontent.com/48310497/63582623-61705080-c5d4-11e9-97ff-fac8a57646ca.jpg)
![3_SITE 20170707_140116](https://user-images.githubusercontent.com/48310497/63582625-61705080-c5d4-11e9-86a4-074ba0a4456a.jpg)
![4_SITE 20170707_134919](https://user-images.githubusercontent.com/48310497/63582626-6208e700-c5d4-11e9-8fe6-f125a7478c8d.jpg)
![5_SITE 20170707_135446](https://user-images.githubusercontent.com/48310497/63582627-6208e700-c5d4-11e9-9a84-b755e59a5d74.jpg)
![6_SITE 20170707_140254](https://user-images.githubusercontent.com/48310497/63582628-6208e700-c5d4-11e9-8dc5-f499f534ea10.jpg)

**Comment by vlaksuga** [comment]
처리함
