### ISSUE TITLE
p_index cotto deste 이미지 변경

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#80]
![image](https://user-images.githubusercontent.com/48310497/63586394-2c67fc00-c5dc-11e9-8099-734831827041.png)
해당 이미지 아래 이미지로 변경
![INDEX - COTTO DESTE](https://user-images.githubusercontent.com/48310497/63586470-53bec900-c5dc-11e9-9afd-319529a730b7.jpg)

**Comment by vlaksuga** [comment]
IMG CHANGE
