### ISSUE TITLE
footer 변경(대문자에서 소문자로 변경)

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#82]
해당 url : footer
변경내용 : 모든 TEL, FAX를 소문자로 변경

**Comment by mufasakang** [comment]
띄어쓰기가 가능하면 띄어쓰기로

**Comment by vlaksuga** [comment]
띄어쓰기 처리함

**Comment by mufasakang** [comment]
![image](https://user-images.githubusercontent.com/48310497/63589407-0181a600-c5e4-11e9-91c1-fd5f4ace1704.png)

1. "본사" 추가
2.  삼패물류센터,경기도 문구 사이에 마진 15px (위의 이천과 같게)

**Comment by vlaksuga** [comment]
확인후 처리요망
