### ISSUE TITLE
p_product 컬렉션명 변경

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#88]
![image](https://user-images.githubusercontent.com/48310497/63671198-d97b8800-c819-11e9-9d97-ec005e459e83.png)

1. 해당 url : p_product, p_produce detail, p_search
2. 참고 url : http://sev.adand.co.kr/?m=product&cid=77
3. 변경내용 : 컬렉션 ID 77번의 이름변경
기존 : MATERICA
변경 : MATERICA 14T

**Comment by vlaksuga** [comment]
적용완료 확인후 클로즈

**Comment by mufasakang** [comment]
확인완료
