### ISSUE TITLE
p_product, project의 서브메뉴에서 ALL을 구분되게 해주세요

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#89]
![image](https://user-images.githubusercontent.com/48310497/63672425-e2ba2400-c81c-11e9-9c0b-080b7cf66c1a.png)
![image](https://user-images.githubusercontent.com/48310497/63672588-37f63580-c81d-11e9-8702-fd94d38d7b94.png)

1. 해당 url : p_project, p_product
2. 참고 url : http://sev.adand.co.kr/?m=projects
3. 내용 : ALL을 잘보이게 해주세요
- font-size:1.0em
  font-weight:bold 로 처리

**Comment by vlaksuga** [comment]
확인후 완료

**Comment by mufasakang** [comment]
확인완료
