### ISSUE TITLE
m=product&cid=1의 타일 디테일오류

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/chinyoung#9]
http://sev.adand.co.kr/?m=product&cid=1
은 0번 데이터를 불러오는 문제인지 확인바랍니다.
아래와 같이 데이터가 나옵니다.
![image](https://user-images.githubusercontent.com/45654321/62865930-aaa9e000-bd4a-11e9-9032-6cafd517013a.png)

**Comment by brilliaflo** [comment]
콜렉션 아이디1인 아이디0번 타일이 있습니다.

**Comment by vlaksuga** [comment]
db 재확인후 클로즈 하겠음

**Comment by vlaksuga** [comment]
확인
