### ISSUE TITLE
footer 문구 수정 (주소,카피라이터)

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#90]
![image](https://user-images.githubusercontent.com/48310497/63673195-b7383900-c81e-11e9-9e2d-7b18bd1046f8.png)

1. 해당 URL : footer
2. 내용 
- 논현점 주소 수정 
 종전 : 서울특별시
 교체 : 서울시

- COPYRIGHT 아래 문구 삽입
-조건
```
<div class="copyright" style=" padding-top: 5px; font-size:0.6em;">
      *본 사이트는 Chrome, Edge에 최적화되어 있습니다.
</div>
```

**Comment by vlaksuga** [comment]
확인후 완료

**Comment by mufasakang** [comment]
-논현점 주소 수정
종전 : 서울특별시
교체 : 서울시

-padding-top: 5px

처리 안됨

**Comment by vlaksuga** [comment]
<br>로 줄바꿈 하고, <span>처리하였으므로
.copyright class에서 line-height:15px로 임의 처리하였음

**Comment by mufasakang** [comment]
확인완료
