### ISSUE TITLE
p_about 글씨스타일 조정

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#91]
![image](https://user-images.githubusercontent.com/48310497/63674073-b0aac100-c820-11e9-8dc0-79c48e9cac65.png)

1. 해당 url : p_about
2. 내용 : `` <p class="story_p" style="font-size:15px; color:#8e8e8e;">CUSTOMER 소비자 문의 / WHOLESALE 유통 문의 / PROJECT 프로젝트 문의</p>``

**Comment by vlaksuga** [comment]
스타일대로 처리함 확인후 완료

**Comment by mufasakang** [comment]
확인완료
