### ISSUE TITLE
p_about OUR HISTORY 내용 수정

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#92]
![image](https://user-images.githubusercontent.com/48310497/63674320-39c1f800-c821-11e9-95c6-28d7fc8195d1.png)

해당 url : p_about
내용 : 아래와 같음

> 

2017.06. PREMIUM TILE GALLERY 프리미엄 타일 갤러리 오픈 - 본사 B1F

2016.08. 코토데스테 (COTTO D’ESTE) 플래그쉽 스토어 오픈 - 본사 1층

2011.03. 본사 및 전시장 신사옥 이전 - 서울시 송파구 삼전로2길 3 (삼전동) 진영빌딩

2010.12. 본사 사옥 매입

2007.07. 제1물류센터 이전 - 경기도 이천시 모가면 송곡2리 166-5 (약 5000평)

2006.01. 논현점 TILE PLAZA 오픈 - 서울시 강남구 학동로24길 16 (논현동 127-7) (35평)

2003.03. 제2물류센터 오픈 - 경기도 남양주시 경강로334번길 48-12 (삼패동 445-4) (약 900평)

2003.02. 제1물류센터 건립

1989.05. ㈜진영코리아 법인설립

**Comment by vlaksuga** [comment]
수정완료

**Comment by mufasakang** [comment]
확인완료
