### ISSUE TITLE
p_about FAQ UI 수정

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#93]
![image](https://user-images.githubusercontent.com/48310497/63676671-6cbaba80-c826-11e9-9177-b937cd64bee9.png)

1. 해당 url : p_about
2. 내용 : Q와 A 글자 다르게 해주세요. (답변글 색조정, 혹은 크기조정) 펼쳤을 때 내용이 한눈에 안들어옴.
3. 제안
-백그라운드 삽입
`<p style="background-color: #4e4e4e;">`

**Comment by vlaksuga** [comment]
제안과 다르게 처리했지만 윗줄 흰색 없애고 제목 뒤에 배경처리함
마우스 오버시와 동일하게 처리함 확인후 처리 요망

**Comment by mufasakang** [comment]
> 제목 뒤에 배경처리함
해당 내용이 확인안됨

**Comment by vlaksuga** [comment]
active 확인후 완료

**Comment by mufasakang** [comment]
확인완료
