### ISSUE TITLE
p_about FAQ 하단의 안내문구 추가

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#94]
![image](https://user-images.githubusercontent.com/48310497/63677456-f6b75300-c827-11e9-91d3-3f7f1accd728.png)

1. 해당 url : p_about
2. 내용 : 안내문구 추가 (작게)

> *사이트에 수록된 이미지와 실제 제품은 모니터 환경에 따라 색상의 차이가 있을 수 있습니다. 정확한 색상은 실제 샘플을 확인해주시기 바랍니다.

3. 제안 : 
``<section id="faq" class="sec_gap">안에
<div><p style="font-size:14px; text-align:center;">*사이트에 수록된 이미지와 실제 제품은 모니터 환경에 따라 색상의 차이가 있을 수 있습니다. 정확한 색상은 실제 샘플을 확인해주시기 바랍니다.</p>
</div>를 추가함``

**Comment by vlaksuga** [comment]
문구추가

**Comment by mufasakang** [comment]
확인완료
