### ISSUE TITLE
p_product  ALL에 active 추가

### ISSUE THREAD

**Issue by mufasakang** [vlaksuga/chinyoung#97]
![image](https://user-images.githubusercontent.com/48310497/63681099-03d84000-c830-11e9-9586-ec636caac737.png)

해당 url : http://sev.adand.co.kr/?m=l
내용 : ALL에 active 추가 부탁드립니다

**Comment by vlaksuga** [comment]
확인완료후

**Comment by vlaksuga** [comment]
확인완료 후 클로즈

**Comment by vlaksuga** [comment]
확인함
